version: '3'

services:
  db:
    image: mysql:8.0.20
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_DATABASE: 'shop'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/bowling-petersburg
      - /var/www/bowling-petersburg/media/:/code/media/
    ports:
      - "8080:8080"
    depends_on:
      - db

